version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: onepod
      POSTGRES_PASSWORD: "DiMFxY0ZpBgWpeW_VFyPF7PMqAc3316_"
    volumes:
      - onepod_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "oC1y96zGqAEQlW5l-z3USav6bHUXd4Qf"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  onepod_data:
